---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-volume
spec:
  containers:
    - image: alpine
      name: alpine
      args:
        - /bin/sh
        - -c
        - sleep 1d
      volumeMounts:
        - mountPath: /var/log
          name: logs-volume
        - mountpath: /data
          name: data-volume

  volumes:
    - name: logs-volume
      emptyDir: {}
    - name: data-volume
      emptyDir: {}


    
